### ISSUE TITLE
'Tensor' object has no attribute 'sparse_read'

### ISSUE THREAD

**Issue by ahseena96** [connorcoley/retrotemp#1]
While training the model, by running 'nntrain_fingerprint' script (following the instructions in README), I get the following error - 

> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2734, in gather
>     return params.sparse_read(indices, name=name)
> AttributeError: 'Tensor' object has no attribute 'sparse_read'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
>     preferred_dtype=default_dtype)
>   File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1104, in internal_convert_to_tensor
>     ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
>   File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 235, in _constant_tensor_conversion_function
>     return constant(v, dtype=dtype, name=name)
>   File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 214, in constant
>     value, dtype=dtype, shape=shape, verify_shape=verify_shape))
>   File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 441, in make_tensor_proto
>     _GetDenseDimensions(values)))
> ValueError: Argument must be a dense tensor: range(0, 1) - got shape [1], but wanted [].
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 524, in _apply_op_helper
>     values, as_ref=input_arg.is_ref).dtype.name
>   File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1104, in internal_convert_to_tensor
>     ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
>   File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 235, in _constant_tensor_conversion_function
>     return constant(v, dtype=dtype, name=name)
>   File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 214, in constant
>     value, dtype=dtype, shape=shape, verify_shape=verify_shape))
>   File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 441, in make_tensor_proto
>     _GetDenseDimensions(values)))
> ValueError: Argument must be a dense tensor: range(0, 1) - got shape [1], but wanted [].
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "retrotemp/nntrain_fingerprint.py", line 90, in <module>
>     mol_hiddens = tf.nn.relu(linearND(input_mol, hidden_size, scope="encoder0"))
>   File "/home/jupyter/notebooks/utils/nn.py", line 22, in linearND
>     X_shape = tf.gather(tf.shape(input_), range(ndim-1))
>   File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2736, in gather
>     return gen_array_ops.gather_v2(params, indices, axis, name=name)
>   File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3065, in gather_v2
>     "GatherV2", params=params, indices=indices, axis=axis, name=name)
>   File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 528, in _apply_op_helper
>     (input_name, err))
> ValueError: Tried to convert 'indices' to a tensor and failed. Error: Argument must be a dense tensor: range(0, 1) - got shape [1], but wanted []

This seems more like a tf problem than retrotemp. Could you please help me with this?

**Comment by connorcoley** [comment]
Hey @ahseena96 -

I'm not sure about the ```sparse_read``` AttributeError, but the other messages point toward Python 2 v. 3 differences that are easy to fix. Throughout the code, there are a few ```range(*)``` function calls, which in Python 2 results in a list object that Tensorflow can convert to a tensor. In Python 3, it results in a range iterator that Tensorflow cannot automatically convert. You can cast it to a list easily with ```list(range(*))``` or possibly switch them to ```np.arange(*)``` calls.

**Comment by ahseena96** [comment]
Thank you, @connorcoley. That helped :)
